### ISSUE TITLE
Módulo npm

### ISSUE THREAD

**Issue by Natalie9** [thr0w/somaReactComponent#1]
Estou em dúvida quanto a utilização do modulo criado semana passada. Ele foi publicado, certo? Então para que eu o utilize no meu projeto eu deveria basicamente rodar "npm install -g @ hoda5/somalib", mas está apresentando um erro como se não pudesse encontrar essa lib

**Comment by gislainy** [comment]
O módulo está como privado no NPM. Para utilizá-lo você deverá (via linha de comando):
 - Fazer login no npm `npm login`
 - Usuário: thr0w 
 - Senha hoda5tecnologia 
 - Email: josefernandotolentino@gmail.com

Acredito que assim irá funcionar

**Comment by joseaugustoneto** [comment]
@Natalie9 não é necessário executar o comando de install com o `-g`, esse parâmetro diz que esse pacote vai ser instalado global e que ele pode ser executado em qualquer lugar na sua máquina, instalamos pacotes assim quando eles vão ser utilizados em muitos projetos.

Execute assim `npm install @hoda5/somalib --save`. o `--save` é para salvar no `package.json`

Não sei se ajudei ou atrapalhei.

@gislainy como o projeto é publico, acho que essa senha que você colocou não é uma boa ideia.

**Comment by Natalie9** [comment]
Ajudou sim @joseaugustoneto, e muito obrigada @gislainy deu certo!
